import { useCallback, useEffect, useMemo, useState } from 'react';
import { BrowserRouter, Link, Navigate, Route, Routes, useLocation, useNavigate } from 'react-router-dom';
import { Activity, ArrowLeft, Bike, Box, Check, ChevronDown, CircleAlert, ClipboardList, DoorOpen, Grid2X2, LoaderCircle, LogIn, MapPin, Package, Plus, RefreshCw, Shield, ShoppingBag, Store, UserRound, Users, X } from 'lucide-react';
import { configured, supabase } from './supabase.js';
import { App as NativeApp } from '@capacitor/app';
import { Capacitor } from '@capacitor/core';

const roles = { customer: 'الزبون', merchant: 'المتجر', courier: 'المندوب', admin: 'الإدارة' };
const orderStatuses = { placed: 'طلب جديد', accepted: 'تم القبول', preparing: 'قيد التجهيز', ready: 'جاهز للاستلام', assigned: 'مع مندوب', picked_up: 'في الطريق', delivered: 'تم التسليم', cancelled: 'ملغي' };
const cash = (n) => new Intl.NumberFormat('ar-EG', { style: 'currency', currency: 'EGP', maximumFractionDigits: 2 }).format(Number(n || 0));
const imagePath = (file) => {
  const extension = (file.name.split('.').pop() || 'jpg').toLowerCase().replace(/[^a-z0-9]/g, '').slice(0, 8) || 'jpg';
  return `${crypto.randomUUID()}.${extension}`;
};
async function uploadStoreAsset(file, path) {
  if (!file || !['image/jpeg', 'image/png', 'image/webp'].includes(file.type)) throw new Error('اختار صورة JPG أو PNG أو WebP.');
  if (file.size > 5 * 1024 * 1024) throw new Error('حجم الصورة يجب ألا يتجاوز 5 ميجابايت.');
  const { error } = await supabase.storage.from('store-assets').upload(path, file, { cacheControl: '3600', upsert: false, contentType: file.type });
  if (error) throw error;
  return supabase.storage.from('store-assets').getPublicUrl(path).data.publicUrl;
}
const niceError = (error) => {
  const message = error?.message || 'حصل خطأ غير متوقع.';
  const map = { 'Invalid login credentials': 'البريد الإلكتروني أو كلمة المرور غير صحيحة.', 'Email not confirmed': 'أكد بريدك الإلكتروني أولًا من الرسالة التي وصلتك.', customer_account_required: 'إنشاء الطلب متاح لحساب الزبون فقط.', merchant_account_required: 'العملية دي لحساب المتجر فقط.', courier_account_required: 'العملية دي لحساب المندوب فقط.', admin_required: 'العملية دي متاحة للإدارة فقط.', product_unavailable: 'في منتج بقى غير متاح. حدّث السلة وحاول تاني.', store_or_delivery_zone_unavailable: 'المتجر أو منطقة التوصيل مش متاحين دلوقتي.', courier_unavailable_or_wrong_zone: 'المندوب مش متاح في منطقة الطلب.', not_assigned_to_you: 'الطلب مش مسند لحسابك.', order_not_ready: 'الطلب لازم يكون جاهز قبل إسناد مندوب.' };
  return map[message] || message;
};

function AuthProvider({ children }) {
  const [session, setSession] = useState(null);
  const [profile, setProfile] = useState(null);
  const [loading, setLoading] = useState(true);
  const [profileError, setProfileError] = useState('');
  const refreshProfile = useCallback(async (userId) => {
    if (!userId || !supabase) { setProfile(null); return null; }
    setProfileError('');
    const { data, error } = await supabase.from('profiles').select('id,full_name,phone,role').eq('id', userId).maybeSingle();
    if (error) { setProfileError(niceError(error)); return null; }
    setProfile(data || null); return data || null;
  }, []);
  useEffect(() => {
    if (!supabase) { setLoading(false); return; }
    let alive = true;
    supabase.auth.getSession().then(async ({ data }) => {
      if (!alive) return;
      setSession(data.session);
      if (data.session?.user) await refreshProfile(data.session.user.id);
      if (alive) setLoading(false);
    });
    const { data: { subscription } } = supabase.auth.onAuthStateChange((_event, next) => {
      setSession(next);
      if (next?.user) {
        setLoading(true);
        queueMicrotask(async () => { await refreshProfile(next.user.id); setLoading(false); });
      } else { setProfile(null); setProfileError(''); setLoading(false); }
    });
    return () => { alive = false; subscription.unsubscribe(); };
  }, [refreshProfile]);
  const value = useMemo(() => ({ session, profile, loading, profileError, refreshProfile }), [session, profile, loading, profileError, refreshProfile]);
  return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>;
}
import { createContext, useContext } from 'react';
const AuthContext = createContext(null);
const useAuth = () => useContext(AuthContext);

function Toast({ message, kind = 'error', clear }) {
  if (!message) return null;
  return <div className={`toast ${kind}`} role="status"><span>{kind === 'error' ? <CircleAlert size={17}/>:<Check size={17}/>}</span><div>{message}</div><button type="button" aria-label="إغلاق" onClick={clear}><X size={16}/></button></div>;
}
function Spinner({ label = 'جاري التحميل' }) { return <div className="spinner-state"><LoaderCircle className="spin" size={22}/><span>{label}</span></div>; }
function Brand({ compact = false }) { return <div className="brand"><span className="brand-mark">و</span><span><strong>وصلة</strong>{!compact && <small>كل احتياجات منطقتك في مكان واحد</small>}</span></div>; }
function AuthGate() {
  const { session, profile, loading, profileError } = useAuth();
  if (loading) return <Spinner label="بنتأكد من حسابك"/>;
  if (!session) return <Navigate to="/login" replace/>;
  if (profileError) return <main className="auth-page"><Brand/><section className="auth-card"><h1>تعذر تحميل الصلاحيات</h1><p>{profileError}</p><button className="button primary" onClick={() => window.location.reload()}>حاول تاني</button></section></main>;
  if (!profile) return <main className="auth-page"><Brand/><section className="auth-card"><h1>حسابك قيد الإعداد</h1><p>ملف المستخدم لسه ما اتجهزش. سجّل الخروج وادخل تاني، أو تواصل مع الإدارة لو استمرت المشكلة.</p><SignOutButton/></section></main>;
  return <OutletGate/>;
}
function OutletGate() { return <Routes><Route path="/customer/*" element={<RoleGuard role="customer"><CustomerApp/></RoleGuard>}/><Route path="/merchant/*" element={<RoleGuard role="merchant"><MerchantApp/></RoleGuard>}/><Route path="/courier/*" element={<RoleGuard role="courier"><CourierApp/></RoleGuard>}/><Route path="/admin/*" element={<RoleGuard role="admin"><AdminApp/></RoleGuard>}/><Route path="*" element={<HomeRedirect/>}/></Routes>; }
function HomeRedirect() { const { profile } = useAuth(); return <Navigate to={profile?.role ? `/${profile.role}` : '/login'} replace/>; }
function RoleGuard({ role, children }) {
  const { profile } = useAuth();
  if (profile?.role !== role) return <Navigate to={profile?.role ? `/${profile.role}` : '/login'} replace/>;
  return children;
}
function SignOutButton() {
  const navigate = useNavigate();
  return <button className="button quiet" onClick={async () => { await supabase.auth.signOut(); navigate('/login'); }}><DoorOpen size={17}/>تسجيل الخروج</button>;
}
function SetupScreen() {
  return <main className="setup-page"><div className="setup-card"><Brand/><p className="eyebrow">نسخة تشغيل قابلة للربط</p><h1>اربط قاعدة بيانات المشروع لبدء التشغيل.</h1><p>أضف رابط Supabase والمفتاح العام إلى <code>public/config.js</code> أو متغيرات البناء، ثم طبّق ملف <code>supabase/schema.sql</code>. التطبيق لا يستبدل بياناتك ببيانات وهمية.</p><ol><li>أنشئ مشروع Supabase.</li><li>ضع Project URL وanon أو publishable key في <code>public/config.js</code>، أو إعدادات الاستضافة.</li><li>شغّل ملف قاعدة البيانات، ثم أنشئ حساب الإدارة حسب README.</li></ol><p className="small-muted">مفتاح service role سري، لا تضفه للواجهة أو ملف .env الخاص بها.</p></div></main>;
}

function LoginPage() {
  const { session, profile, loading } = useAuth(); const navigate = useNavigate();
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  if (loading) return <Spinner label="بنتأكد من حسابك"/>;
  if (!loading && session && profile?.role) return <Navigate to={`/${profile.role}`} replace/>;
  async function submit(e) { e.preventDefault(); setBusy(true); setError(''); const { error: err } = await supabase.auth.signInWithPassword({ email: email.trim(), password }); if (err) setError(niceError(err)); else navigate('/'); setBusy(false); }
  return <main className="auth-page"><Brand/><section className="auth-card"><span className="eyebrow">دخول آمن</span><h1>سجّل دخولك</h1><p>كل مستخدم يدخل على النظام المخصص لدوره.</p><form onSubmit={submit} className="form-stack"><label>البريد الإلكتروني<input autoComplete="email" type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@example.com"/></label><label>كلمة المرور<input autoComplete="current-password" type="password" minLength="8" required value={password} onChange={e=>setPassword(e.target.value)}/></label><Toast message={error} clear={()=>setError('')}/><button className="button primary full" disabled={busy}>{busy?<LoaderCircle className="spin" size={17}/>:<LogIn size={17}/>}دخول</button></form><p className="auth-switch">أول مرة؟ <Link to="/signup">اعمل حساب زبون</Link></p><p className="small-muted">حسابات المتجر والمندوب تنشئها الإدارة. ما فيش اختيار دور من شاشة التسجيل.</p></section><Footer/></main>;
}
function SignupPage() {
  const { session, profile, loading } = useAuth(); const [name,setName]=useState('');const [phone,setPhone]=useState('');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [done,setDone]=useState(false);
  if (loading) return <Spinner label="بنتأكد من حسابك"/>;
  if (session && profile?.role) return <Navigate to={`/${profile.role}`} replace/>;
  async function submit(e){e.preventDefault();setBusy(true);setError('');const {error:err}=await supabase.auth.signUp({email:email.trim(),password,options:{data:{full_name:name.trim(),phone:phone.trim()},emailRedirectTo:Capacitor.isNativePlatform()?'com.wosla.delivery://auth-callback':`${window.location.origin}/login`}});if(err)setError(niceError(err));else {setDone(true);}setBusy(false);}
  return <main className="auth-page"><Brand/><section className="auth-card"><span className="eyebrow">حساب زبون</span><h1>{done?'راجع بريدك الإلكتروني':'اعمل حساب جديد'}</h1>{done?<p>لو تأكيد البريد مفعّل، هتوصلك رسالة تفعيل. بعد التفعيل ارجع وسجّل الدخول.</p>:<><p>حسابات المتاجر والمناديب بتتعمل بدعوة من الإدارة.</p><form onSubmit={submit} className="form-stack"><label>الاسم<input required value={name} onChange={e=>setName(e.target.value)} autoComplete="name"/></label><label>رقم الموبايل<input value={phone} onChange={e=>setPhone(e.target.value)} autoComplete="tel" inputMode="tel"/></label><label>البريد الإلكتروني<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email"/></label><label>كلمة المرور<input type="password" required minLength="8" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="new-password"/><small>٨ أحرف على الأقل</small></label><Toast message={error} clear={()=>setError('')}/><button className="button primary full" disabled={busy}>{busy?<LoaderCircle className="spin" size={17}/>:<UserRound size={17}/>}إنشاء حساب زبون</button></form></>}<p className="auth-switch">عندك حساب؟ <Link to="/login">سجّل دخولك</Link></p></section><Footer/></main>;
}
function Footer(){return <footer className="footer">وصلة · طلبات محلية من متاجر منطقتك</footer>}
function Shell({role, title, subtitle, children}) {
  const {profile}=useAuth();
  return <div className="app-shell"><header className="topbar"><Link to={`/${role}`} className="brand-link"><Brand compact/></Link><div className="top-meta"><span className="role-stamp">{roles[role]}</span><span className="user-name">{profile?.full_name||profile?.id?.slice(0,8)}</span><SignOutButton/></div></header><main className="main-content"><header className="page-heading"><div><span className="eyebrow">{roles[role]}</span><h1>{title}</h1><p>{subtitle}</p></div></header>{children}</main><Footer/></div>;
}
function useRemote(load, deps=[]) {
  const [data,setData]=useState(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const refresh=useCallback(async()=>{setLoading(true);setError('');try{const value=await load();setData(value);}catch(e){setError(niceError(e));}finally{setLoading(false);}},deps);
  useEffect(()=>{refresh();},[refresh]);
  useEffect(()=>{const timer=setInterval(refresh,20000);return()=>clearInterval(timer);},[refresh]);
  return {data,loading,error,refresh,setData};
}
function unwrap(result){if(result.error)throw result.error;return result.data;}
function ErrorBlock({error,retry}){return <div className="error-block"><CircleAlert size={18}/><span>{error}</span>{retry&&<button className="button quiet" onClick={retry}><RefreshCw size={15}/>إعادة المحاولة</button>}</div>}
function LoadingBlock(){return <Spinner/>}
function Empty({children}){return <div className="empty-state"><Package size={22}/><span>{children}</span></div>}
function Status({status}){return <span className={`status status-${status}`}>{orderStatuses[status]||status}</span>}
function Panel({title,aside,children}){return <section className="panel"><div className="panel-head"><h2>{title}</h2>{aside}</div>{children}</section>}
function useZones(){return useRemote(async()=>unwrap(await supabase.from('delivery_zones').select('id,name,fee,active').eq('active',true).order('name')) ,[]);}
function useStoresForCustomer(){return useRemote(async()=>unwrap(await supabase.from('stores').select('id,name,category,description,image_url,zone_id,delivery_zones(name,fee)').eq('active',true).order('name')) ,[]);}
function ProductCard({product,onAdd,disabled}){return <article className="product-card">{product.image_url&&<img className="catalog-image" src={product.image_url} alt={product.name} loading="lazy"/>}<div className="product-top"><span className="category-tag">{product.category}</span><strong>{cash(product.price)}</strong></div><h3>{product.name}</h3><p>{product.description||'منتج من متجر محلي'}</p><button className="button outline full" onClick={()=>onAdd(product)} disabled={disabled}><Plus size={16}/>أضف للسلة</button></article>}
function CustomerApp(){
  const {profile}=useAuth();const {data:zones,loading:zonesLoading,error:zonesError,refresh:refreshZones}=useZones();const [zoneId,setZoneId]=useState('');const [storeId,setStoreId]=useState('');const [cart,setCart]=useState([]);const [address,setAddress]=useState('');const [note,setNote]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');
  const {data:stores,loading:storesLoading,error:storesError,refresh:refreshStores}=useStoresForCustomer();
  useEffect(()=>{if(zones?.length&&!zoneId)setZoneId(zones[0].id);},[zones,zoneId]);
  const selectedStore=stores?.find(s=>s.id===storeId);const visibleStores=(stores||[]).filter(s=>s.zone_id===zoneId);const productsState=useRemote(async()=>{if(!storeId)return [];return unwrap(await supabase.from('products').select('id,store_id,name,description,category,price,image_url').eq('store_id',storeId).eq('active',true).order('name'));},[storeId]);
  const ordersState=useRemote(async()=>unwrap(await supabase.from('orders').select('id,order_number,status,total,delivery_fee,created_at,stores(name),order_items(product_name,quantity,unit_price)').eq('customer_id',profile.id).order('created_at',{ascending:false}).limit(15)),[profile.id]);
  const subtotal=cart.reduce((sum,item)=>sum+Number(item.price)*item.quantity,0);const deliveryFee=Number(zones?.find(z=>z.id===zoneId)?.fee||0);
  function add(product){if(cart.length&&cart[0].store_id!==product.store_id){setError('كل طلب من متجر واحد. أفرغ السلة الأول لو عايز تطلب من متجر تاني.');return;}setError('');setCart(current=>{const found=current.find(p=>p.id===product.id);return found?current.map(p=>p.id===product.id?{...p,quantity:p.quantity+1}:p):[...current,{...product,quantity:1}];});}
  function changeQty(id,delta){setCart(current=>current.map(p=>p.id===id?{...p,quantity:p.quantity+delta}:p).filter(p=>p.quantity>0));}
  async function checkout(){setError('');setMessage('');if(!cart.length||!address.trim()){setError('أضف منتجات واكتب عنوان التوصيل.');return;}setBusy(true);const {data,error:err}=await supabase.rpc('place_order',{p_store_id:cart[0].store_id,p_zone_id:zoneId,p_address:address.trim(),p_note:note.trim(),p_items:cart.map(p=>({product_id:p.id,quantity:p.quantity}))});if(err)setError(niceError(err));else{setMessage(`اتسجل الطلب رقم ${String(data).slice(0,8)} بنجاح.`);setCart([]);setAddress('');setNote('');ordersState.refresh();}setBusy(false);}
  return <Shell role="customer" title="اطلب من منطقتك" subtitle="اطلب من متجر واحد في كل مرة، ورسوم التوصيل تظهر قبل التأكيد.">
    <div className="toolbar"><label className="field-label">منطقة التوصيل<select value={zoneId} onChange={e=>{setZoneId(e.target.value);setStoreId('');setCart([]);}}>{(zones||[]).map(z=><option value={z.id} key={z.id}>{z.name} · {cash(z.fee)}</option>)}</select></label><label className="field-label">المتجر<select value={storeId} onChange={e=>{setStoreId(e.target.value);setCart([]);}}><option value="">اختار متجرًا</option>{visibleStores.map(s=><option value={s.id} key={s.id}>{s.name} · {s.category}</option>)}</select></label></div>
    {(zonesError||storesError)&&<ErrorBlock error={zonesError||storesError} retry={()=>{refreshZones();refreshStores();}}/>}{zonesLoading||storesLoading?<LoadingBlock/>:!zones?.length?<Empty>مفيش مناطق توصيل نشطة حاليًا. راجع الإدارة.</Empty>:!visibleStores.length?<Empty>مفيش متاجر مفتوحة في المنطقة المختارة دلوقتي.</Empty>:null}
    {selectedStore&&<section className="selected-store-card">{selectedStore.image_url&&<img src={selectedStore.image_url} alt={selectedStore.name} loading="lazy"/>}<div><span className="category-tag">{selectedStore.category}</span><h2>{selectedStore.name}</h2><p>{selectedStore.description||'متجر محلي في منطقتك'}</p></div></section>}
    {storeId&&<section className="product-grid">{productsState.loading?<LoadingBlock/>:productsState.error?<ErrorBlock error={productsState.error} retry={productsState.refresh}/>:productsState.data?.length?productsState.data.map(p=><ProductCard key={p.id} product={p} onAdd={add}/>):<Empty>المتجر ما أضافش منتجات متاحة حاليًا.</Empty>}</section>}
    {cart.length>0&&<Panel title="سلتك"><div className="cart-list">{cart.map(p=><div className="cart-line" key={p.id}><div><strong>{p.name}</strong><small>{cash(p.price)} للقطعة</small></div><div className="quantity"><button aria-label="تقليل الكمية" onClick={()=>changeQty(p.id,-1)}>−</button><span>{p.quantity}</span><button aria-label="زيادة الكمية" onClick={()=>changeQty(p.id,1)}>+</button></div><strong>{cash(p.price*p.quantity)}</strong></div>)}</div><label className="field-label">عنوان التوصيل<input value={address} onChange={e=>setAddress(e.target.value)} placeholder="الشارع، علامة مميزة، القرية" required/></label><label className="field-label">ملاحظة للمتجر أو المندوب<input value={note} onChange={e=>setNote(e.target.value)} placeholder="اختياري"/></label><div className="totals"><span>المنتجات</span><strong>{cash(subtotal)}</strong><span>التوصيل</span><strong>{cash(deliveryFee)}</strong><span className="total-label">الإجمالي · الدفع نقدًا عند الاستلام</span><strong className="total-value">{cash(subtotal+deliveryFee)}</strong></div><Toast message={error} clear={()=>setError('')}/>{message&&<Toast kind="success" message={message} clear={()=>setMessage('')}/>}<button className="button primary full" onClick={checkout} disabled={busy}>{busy?<LoaderCircle size={17} className="spin"/>:<ShoppingBag size={17}/>}تأكيد الطلب</button></Panel>}
    <OrdersPanel state={ordersState} title="طلباتي" customer/>
  </Shell>;
}
function OrdersPanel({state,title,customer=false,children}){if(state.loading)return <Panel title={title}><LoadingBlock/></Panel>;if(state.error)return <Panel title={title}><ErrorBlock error={state.error} retry={state.refresh}/></Panel>;return <Panel title={title} aside={<button className="button quiet" onClick={state.refresh}><RefreshCw size={15}/>تحديث</button>}>{state.data?.length?<div className="order-list">{state.data.map(order=><OrderRow key={order.id} order={order} customer={customer}>{children?.(order)}</OrderRow>)}</div>:<Empty>مفيش طلبات لسه.</Empty>}</Panel>;}
function OrderRow({order,children}){return <article className="order-row"><div className="order-main"><div className="order-row-title"><strong>طلب #{order.order_number||order.id.slice(0,8)}</strong><Status status={order.status}/></div><p>{order.stores?.name||'متجر'} · {new Date(order.created_at).toLocaleString('ar-EG')}</p>{order.order_items?.length>0&&<small>{order.order_items.map(i=>`${i.product_name} × ${i.quantity}`).join('، ')}</small>}</div><div className="order-side"><strong>{cash(order.total)}</strong>{children}</div></article>;}

function MerchantApp(){const {profile}=useAuth();const [storeId,setStoreId]=useState('');const [draft,setDraft]=useState({name:'',category:'أكل',description:'',price:'',imageFile:null});const [productPreview,setProductPreview]=useState('');const [storeDraft,setStoreDraft]=useState({description:'',imageFile:null});const [message,setMessage]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const storesState=useRemote(async()=>unwrap(await supabase.from('stores').select('id,name,category,description,image_url,active,zone_id,delivery_zones(name)').eq('owner_id',profile.id).order('name')),[profile.id]);
 useEffect(()=>{if(storesState.data?.length&&!storeId)setStoreId(storesState.data[0].id);},[storesState.data,storeId]);const store=storesState.data?.find(s=>s.id===storeId);useEffect(()=>{if(store)setStoreDraft({description:store.description||'',imageFile:null});},[storeId,store?.description]);
 const productsState=useRemote(async()=>storeId?unwrap(await supabase.from('products').select('*').eq('store_id',storeId).order('created_at',{ascending:false})):[],[storeId]);
 const ordersState=useRemote(async()=>storeId?unwrap(await supabase.from('orders').select('id,order_number,status,total,created_at,order_items(product_name,quantity,unit_price)').eq('store_id',storeId).order('created_at',{ascending:false}).limit(40)):[],[storeId]);
 async function saveProduct(e){e.preventDefault();setError('');setMessage('');setBusy(true);let uploadedPath='';try{let image_url=null;if(draft.imageFile){uploadedPath=`products/${storeId}/${imagePath(draft.imageFile)}`;image_url=await uploadStoreAsset(draft.imageFile,uploadedPath);}const {error:err}=await supabase.from('products').insert({store_id:storeId,name:draft.name.trim(),category:draft.category,description:draft.description.trim(),price:Number(draft.price),image_url,active:true});if(err)throw err;setMessage('اتضاف المنتج وصورته واتحفظوا في قاعدة البيانات.');setDraft({name:'',category:store?.category||'أكل',description:'',price:'',imageFile:null});setProductPreview('');const imageInput=document.getElementById('merchant-product-image');if(imageInput)imageInput.value='';productsState.refresh();}catch(err){if(uploadedPath)await supabase.storage.from('store-assets').remove([uploadedPath]);setError(niceError(err));}finally{setBusy(false);}}
 async function setActive(id,active){const {error:err}=await supabase.from('products').update({active}).eq('id',id);if(err)setError(niceError(err));else productsState.refresh();}
 async function changeStatus(order,status){const {error:err}=await supabase.rpc('merchant_set_order_status',{p_order_id:order.id,p_status:status});if(err)setError(niceError(err));else{setMessage(`تم تحديث حالة الطلب #${order.order_number}.`);ordersState.refresh();}}
 async function setStoreActive(active){const {error:err}=await supabase.from('stores').update({active}).eq('id',storeId);if(err)setError(niceError(err));else storesState.refresh();}
 async function saveStoreProfile(e){e.preventDefault();if(!store)return;setError('');setMessage('');setBusy(true);let uploadedPath='';try{let image_url=store.image_url||null;if(storeDraft.imageFile){uploadedPath=`stores/${storeId}/${imagePath(storeDraft.imageFile)}`;image_url=await uploadStoreAsset(storeDraft.imageFile,uploadedPath);}const {error:err}=await supabase.from('stores').update({description:storeDraft.description.trim(),image_url}).eq('id',storeId);if(err)throw err;setMessage('اتحفظت بيانات المتجر وصورته في قاعدة البيانات.');setStoreDraft(current=>({...current,imageFile:null}));const storeInput=document.getElementById('merchant-store-image');if(storeInput)storeInput.value='';storesState.refresh();}catch(err){if(uploadedPath)await supabase.storage.from('store-assets').remove([uploadedPath]);setError(niceError(err));}finally{setBusy(false);}}
 return <Shell role="merchant" title="بوابة المتجر" subtitle="أضف منتجاتك، حدّث التوفر، وتابع طلبات متجرك فقط.">
  {storesState.error?<ErrorBlock error={storesState.error} retry={storesState.refresh}/>:storesState.loading?<LoadingBlock/>:!storesState.data?.length?<Empty>مافيش متجر مربوط بحسابك. اطلب من الإدارة إنشاء متجر وربطه بحسابك.</Empty>:<>
   <div className="toolbar"><label className="field-label">متاجري<select value={storeId} onChange={e=>setStoreId(e.target.value)}>{storesState.data.map(s=><option key={s.id} value={s.id}>{s.name} · {s.delivery_zones?.name}</option>)}</select></label><button className={`button ${store?.active?'outline':'primary'}`} onClick={()=>setStoreActive(!store?.active)}>{store?.active?'إيقاف المتجر':'فتح المتجر'}</button></div>
   <Toast message={error} clear={()=>setError('')}/>{message&&<Toast kind="success" message={message} clear={()=>setMessage('')}/>}
   <Panel title="بيانات المتجر"><div className="store-profile-editor">{store?.image_url&&<img className="store-profile-image" src={store.image_url} alt={store.name}/>}<form className="form-grid" onSubmit={saveStoreProfile}><label className="field-label field-wide">نبذة المتجر<textarea rows="3" value={storeDraft.description} onChange={e=>setStoreDraft({...storeDraft,description:e.target.value})} placeholder="اكتب نبذة تظهر للزبائن"/></label><label className="field-label field-wide">صورة المتجر<input id="merchant-store-image" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>5*1024*1024){setError('حجم الصورة يجب ألا يتجاوز 5 ميجابايت.');e.target.value='';return;}setStoreDraft({...storeDraft,imageFile:file});}}/><small>JPG أو PNG أو WebP، بحد أقصى 5 ميجابايت</small></label>{storeDraft.imageFile&&<div className="field-wide selected-file">الصورة المختارة: {storeDraft.imageFile.name}</div>}<button className="button primary" disabled={busy}><Check size={17}/>حفظ بيانات المتجر</button></form></div></Panel>
   <Panel title="إضافة منتج"><form className="form-grid" onSubmit={saveProduct}><label className="field-label">اسم المنتج<input required value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label className="field-label">التصنيف<select value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}>{['أكل','بقالة','صيدلية','إلكترونيات','ورد وهدايا','أخرى'].map(c=><option key={c}>{c}</option>)}</select></label><label className="field-label">السعر بالجنيه<input type="number" min="0.01" step="0.01" required value={draft.price} onChange={e=>setDraft({...draft,price:e.target.value})}/></label><label className="field-label">وصف المنتج<input value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label className="field-label field-wide">صورة المنتج<input id="merchant-product-image" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>5*1024*1024){setError('حجم الصورة يجب ألا يتجاوز 5 ميجابايت.');e.target.value='';return;}setDraft({...draft,imageFile:file});setProductPreview(URL.createObjectURL(file));}}/><small>JPG أو PNG أو WebP، بحد أقصى 5 ميجابايت</small></label>{productPreview&&<img className="product-preview-image field-wide" src={productPreview} alt="معاينة صورة المنتج"/>}<button className="button primary" disabled={busy}><Plus size={17}/>حفظ المنتج</button></form></Panel>
   <Panel title="منتجات المتجر" aside={<button className="button quiet" onClick={productsState.refresh}><RefreshCw size={15}/>تحديث</button>}>{productsState.loading?<LoadingBlock/>:productsState.error?<ErrorBlock error={productsState.error} retry={productsState.refresh}/>:productsState.data?.length?<div className="order-list">{productsState.data.map(p=><div className="order-row" key={p.id}>{p.image_url&&<img className="product-thumb" src={p.image_url} alt="" loading="lazy"/>}<div className="order-main"><strong>{p.name}</strong><p>{p.category} · {cash(p.price)}</p></div><button className={`button ${p.active?'outline':'quiet'}`} onClick={()=>setActive(p.id,!p.active)}>{p.active?'إيقاف':'إظهار'}</button></div>)}</div>:<Empty>أضف أول منتج للمتجر.</Empty>}</Panel>
   <OrdersPanel state={ordersState} title="طلبات المتجر" >{order=>{const next={placed:'accepted',accepted:'preparing',preparing:'ready'}[order.status];return next?<button className="button primary small" onClick={()=>changeStatus(order,next)}>{({accepted:'قبول الطلب',preparing:'بدء التجهيز',ready:'جاهز للاستلام'})[next]}</button>:null;}}</OrdersPanel>
  </>}
 </Shell>;
}
function CourierApp(){const {profile}=useAuth();const [available,setAvailable]=useState(false);const [courier,setCourier]=useState(null);const [error,setError]=useState('');const [message,setMessage]=useState('');
 const profileState=useRemote(async()=>{const data=unwrap(await supabase.from('courier_profiles').select('user_id,zone_id,available,vehicle,delivery_zones(name)').eq('user_id',profile.id).maybeSingle());setCourier(data);setAvailable(Boolean(data?.available));return data;},[profile.id]);
 const ordersState=useRemote(async()=>unwrap(await supabase.from('orders').select('id,order_number,status,total,address,created_at,stores(name),order_items(product_name,quantity)').eq('courier_id',profile.id).in('status',['assigned','picked_up']).order('created_at',{ascending:false})),[profile.id]);
 async function toggleAvailable(){if(!courier)return;const value=!available;const {error:err}=await supabase.from('courier_profiles').update({available:value}).eq('user_id',profile.id);if(err)setError(niceError(err));else{setAvailable(value);profileState.refresh();}}
 async function advance(order,status){const {error:err}=await supabase.rpc('courier_set_order_status',{p_order_id:order.id,p_status:status});if(err)setError(niceError(err));else{setMessage(`اتحدّث الطلب #${order.order_number}.`);ordersState.refresh();profileState.refresh();}}
 return <Shell role="courier" title="تطبيق المندوب" subtitle="شوف الطلبات المسندة ليك، وحدّثها من الاستلام لحد التسليم.">
  {error&&<Toast message={error} clear={()=>setError('')}/ >}{message&&<Toast kind="success" message={message} clear={()=>setMessage('')}/>}
  {profileState.loading?<LoadingBlock/>:profileState.error?<ErrorBlock error={profileState.error} retry={profileState.refresh}/>:!courier?<Empty>حسابك محتاج ربط بملف مندوب ومنطقة توصيل من الإدارة.</Empty>:<Panel title="حسابي"><div className="courier-card"><div><span className="muted">منطقة العمل</span><strong>{courier.delivery_zones?.name||'غير محددة'}</strong><span className="muted">{courier.vehicle}</span></div><button className={`button ${available?'outline':'primary'}`} onClick={toggleAvailable}>{available?'إيقاف التوفر':'بدء التوفر'}</button></div><p className="small-muted">يتوقف قبول مهام جديدة أثناء انشغالك بطلب مسند إليك.</p></Panel>}
  <OrdersPanel state={ordersState} title="مهامي الحالية">{order=>order.status==='assigned'?<button className="button primary small" onClick={()=>advance(order,'picked_up')}>استلمت الطلب</button>:order.status==='picked_up'?<button className="button primary small" onClick={()=>advance(order,'delivered')}>تم التسليم</button>:null}</OrdersPanel>
 </Shell>;
}

function AdminApp(){
 const [tab,setTab]=useState('orders');const [error,setError]=useState('');const [message,setMessage]=useState('');const [storeImage,setStoreImage]=useState(null);const [storePreview,setStorePreview]=useState('');const [zoneDraft,setZoneDraft]=useState({name:'',fee:''});const [storeDraft,setStoreDraft]=useState({owner_id:'',zone_id:'',name:'',category:'أكل',description:''});const [courierDraft,setCourierDraft]=useState({user_id:'',zone_id:'',vehicle:'دراجة نارية'});const [busy,setBusy]=useState(false);
 const ordersState=useRemote(async()=>unwrap(await supabase.from('orders').select('id,order_number,status,total,address,created_at,zone_id,store_id,courier_id,stores(name),delivery_zones(name),order_items(product_name,quantity)').order('created_at',{ascending:false}).limit(100)),[]);
 const zonesState=useRemote(async()=>unwrap(await supabase.from('delivery_zones').select('*').order('name')),[]);
 const usersState=useRemote(async()=>unwrap(await supabase.from('profiles').select('id,full_name,phone,role,created_at').order('created_at',{ascending:false}).limit(200)),[]);
 const couriersState=useRemote(async()=>unwrap(await supabase.from('courier_profiles').select('user_id,zone_id,available,vehicle,profiles(full_name,phone),delivery_zones(name)').order('available',{ascending:false})),[]);
 const storesState=useRemote(async()=>unwrap(await supabase.from('stores').select('id,name,category,description,image_url,active,owner_id,zone_id,profiles(full_name),delivery_zones(name)').order('created_at',{ascending:false})),[]);
 const ready=(ordersState.data||[]).filter(o=>o.status==='ready');const live=(ordersState.data||[]).filter(o=>!['delivered','cancelled'].includes(o.status));const drivers=(couriersState.data||[]).filter(c=>c.available);
 async function run(action,success,reload=[]){setError('');setMessage('');setBusy(true);try{await action();setMessage(success);reload.forEach(f=>f());}catch(e){setError(niceError(e));}finally{setBusy(false);}}
 async function assign(order,event){const courierId=event.target.value;if(!courierId)return;await run(async()=>unwrap(await supabase.rpc('assign_courier',{p_order_id:order.id,p_courier_id:courierId})),`تم إسناد الطلب #${order.order_number} للمندوب.`,[ordersState.refresh,couriersState.refresh]);event.target.value='';}
 async function addZone(e){e.preventDefault();await run(async()=>unwrap(await supabase.from('delivery_zones').insert({name:zoneDraft.name.trim(),fee:Number(zoneDraft.fee),active:false})), 'اتضافت المنطقة. راجعها وفعّلها بعد تحديد الرسوم والتغطية.',[zonesState.refresh]);setZoneDraft({name:'',fee:''});}
 async function toggleZone(zone){await run(async()=>unwrap(await supabase.from('delivery_zones').update({active:!zone.active}).eq('id',zone.id)),zone.active?'اتوقفت منطقة التوصيل.':'اتفعّلت منطقة التوصيل.',[zonesState.refresh]);}
 async function setRole(user,role){await run(async()=>unwrap(await supabase.rpc('admin_set_user_role',{p_user_id:user.id,p_role:role})),`اتحدّث دور ${user.full_name||user.id.slice(0,8)}.`,[usersState.refresh,couriersState.refresh]);}
 async function addStore(e){e.preventDefault();setError('');setMessage('');setBusy(true);let uploadedPath='';try{let image_url=null;if(storeImage){uploadedPath=`stores/${crypto.randomUUID()}/${imagePath(storeImage)}`;image_url=await uploadStoreAsset(storeImage,uploadedPath);}const {error:err}=await supabase.from('stores').insert({owner_id:storeDraft.owner_id,zone_id:storeDraft.zone_id,name:storeDraft.name.trim(),category:storeDraft.category,description:storeDraft.description.trim(),image_url,active:false});if(err)throw err;setMessage('اتسجل المتجر وبياناته وصورته في قاعدة البيانات، وهو موقوف لحين المراجعة.');storesState.refresh();usersState.refresh();setStoreDraft({owner_id:'',zone_id:'',name:'',category:'أكل',description:''});setStoreImage(null);setStorePreview('');}catch(err){if(uploadedPath)await supabase.storage.from('store-assets').remove([uploadedPath]);setError(niceError(err));}finally{setBusy(false);}}
 async function addCourier(e){e.preventDefault();await run(async()=>{unwrap(await supabase.from('courier_profiles').insert({user_id:courierDraft.user_id,zone_id:courierDraft.zone_id,vehicle:courierDraft.vehicle,available:false}));},'اتعمل ملف المندوب، وهو غير متاح لحد ما يبدأ ورديته.',[couriersState.refresh,usersState.refresh]);setCourierDraft({user_id:'',zone_id:'',vehicle:'دراجة نارية'});}
 const reloadAll=()=>[ordersState.refresh,zonesState.refresh,usersState.refresh,couriersState.refresh,storesState.refresh].forEach(f=>f());
 return <Shell role="admin" title="مركز التشغيل" subtitle="تابع الطلبات، عرّف مناطق العمل، وجهّز حسابات المتاجر والمناديب.">
  <div className="metric-grid"><Metric label="طلبات مفتوحة" value={live.length} icon={<ClipboardList/>}/><Metric label="جاهزة للإسناد" value={ready.length} icon={<Bike/>}/><Metric label="مناديب متاحون" value={drivers.length} icon={<Activity/>}/><Metric label="متاجر مسجلة" value={storesState.data?.length??'—'} icon={<Store/>}/></div>
  <Toast message={error} clear={()=>setError('')}/>{message&&<Toast kind="success" message={message} clear={()=>setMessage('')}/>}
  <nav className="admin-tabs" aria-label="أقسام الإدارة">{[['orders','الطلبات'],['accounts','الحسابات'],['zones','مناطق التوصيل']].map(([id,label])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}>{label}</button>)}<button className="tab-refresh" onClick={reloadAll}><RefreshCw size={15}/>تحديث</button></nav>
  {tab==='orders'&&<div className="admin-columns"><OrdersPanel state={ordersState} title="طلبات التشغيل" >{order=>order.status==='ready'?<label className="assign-select"><span>إسناد</span><select defaultValue="" disabled={!drivers.length||busy} onChange={e=>assign(order,e)}><option value="">{drivers.length?'اختار مندوبًا':'لا يوجد مندوب متاح'}</option>{drivers.filter(d=>d.zone_id===order.zone_id).map(d=><option key={d.user_id} value={d.user_id}>{d.profiles?.full_name||d.user_id.slice(0,7)} · {d.delivery_zones?.name}</option>)}</select></label>:null}</OrdersPanel><Panel title="جاهزة للتوصيل"><p className="small-muted">لا يظهر للمندوب إلا الطلب المسند إليه، وتحدد قاعدة البيانات أن يكون متاحًا وفي نفس منطقة الطلب.</p>{ready.length?<div className="order-list">{ready.map(o=><div className="order-row" key={o.id}><div><strong>#{o.order_number}</strong><p>{o.stores?.name} · {o.delivery_zones?.name}</p></div><Status status={o.status}/></div>)}</div>:<Empty>مفيش طلبات جاهزة حاليًا.</Empty>}</Panel></div>}
  {tab==='accounts'&&<div className="admin-columns"><Panel title="حسابات المستخدمين" aside={<span className="small-muted">ترقية الدور لا تنشئ بيانات دخول جديدة</span>}>{usersState.loading?<LoadingBlock/>:usersState.error?<ErrorBlock error={usersState.error} retry={usersState.refresh}/>:usersState.data?.length?<div className="user-list">{usersState.data.map(user=><div className="user-row" key={user.id}><div><strong>{user.full_name||'بدون اسم'}</strong><small>{user.phone||user.id.slice(0,8)}</small></div><select value={user.role} onChange={e=>setRole(user,e.target.value)} disabled={busy||user.role==='admin'} aria-label={`دور ${user.full_name}`}><option value="customer">زبون</option><option value="merchant">متجر</option><option value="courier">مندوب</option><option value="admin">إدارة</option></select></div>)}</div>:<Empty>مفيش حسابات.</Empty>}</Panel>
   <div className="stack-panels"><Panel title="إنشاء متجر"><form className="form-stack compact-form" onSubmit={addStore}><label className="field-label">حساب صاحب المتجر<select required value={storeDraft.owner_id} onChange={e=>setStoreDraft({...storeDraft,owner_id:e.target.value})}><option value="">اختار حساب متجر</option>{(usersState.data||[]).filter(u=>u.role==='merchant').map(u=><option key={u.id} value={u.id}>{u.full_name||u.id.slice(0,8)}</option>)}</select></label><label className="field-label">اسم المتجر<input required value={storeDraft.name} onChange={e=>setStoreDraft({...storeDraft,name:e.target.value})}/></label><label className="field-label">المنطقة<select required value={storeDraft.zone_id} onChange={e=>setStoreDraft({...storeDraft,zone_id:e.target.value})}><option value="">اختار منطقة</option>{(zonesState.data||[]).map(z=><option key={z.id} value={z.id}>{z.name}</option>)}</select></label><label className="field-label">التصنيف<input required value={storeDraft.category} onChange={e=>setStoreDraft({...storeDraft,category:e.target.value})}/></label><label className="field-label">نبذة المتجر<textarea rows="2" value={storeDraft.description} onChange={e=>setStoreDraft({...storeDraft,description:e.target.value})} placeholder="نبذة تظهر للزبائن"/></label><label className="field-label">صورة المتجر<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>5*1024*1024){setError('حجم الصورة يجب ألا يتجاوز 5 ميجابايت.');e.target.value='';return;}setStoreImage(file);setStorePreview(URL.createObjectURL(file));}}/><small>JPG أو PNG أو WebP، بحد أقصى 5 ميجابايت</small></label>{storePreview&&<img className="store-preview-image" src={storePreview} alt="معاينة صورة المتجر"/>}<button className="button primary" disabled={busy}><Plus size={16}/>إنشاء متجر وحفظ صورته</button></form></Panel>
   <Panel title="ربط مندوب بمنطقة"><form className="form-stack compact-form" onSubmit={addCourier}><label className="field-label">حساب المندوب<select required value={courierDraft.user_id} onChange={e=>setCourierDraft({...courierDraft,user_id:e.target.value})}><option value="">اختار حساب مندوب</option>{(usersState.data||[]).filter(u=>u.role==='courier'&&!(couriersState.data||[]).some(c=>c.user_id===u.id)).map(u=><option key={u.id} value={u.id}>{u.full_name||u.id.slice(0,8)}</option>)}</select></label><label className="field-label">منطقة العمل<select required value={courierDraft.zone_id} onChange={e=>setCourierDraft({...courierDraft,zone_id:e.target.value})}><option value="">اختار منطقة</option>{(zonesState.data||[]).map(z=><option key={z.id} value={z.id}>{z.name}</option>)}</select></label><label className="field-label">وسيلة التوصيل<input value={courierDraft.vehicle} onChange={e=>setCourierDraft({...courierDraft,vehicle:e.target.value})}/></label><button className="button primary" disabled={busy}><Plus size={16}/>إضافة ملف مندوب</button></form></Panel></div></div>}
  {tab==='zones'&&<div className="admin-columns"><Panel title="مناطق التوصيل" aside={<span className="small-muted">المناطق الجديدة تبدأ متوقفة</span>}>
    {zonesState.loading?<LoadingBlock/>:zonesState.error?<ErrorBlock error={zonesState.error} retry={zonesState.refresh}/>:zonesState.data?.length?<div className="order-list">{zonesState.data.map(zone=><div className="order-row" key={zone.id}><div className="order-main"><strong>{zone.name}</strong><p>رسوم التوصيل: {cash(zone.fee)}</p></div><button className={`button ${zone.active?'outline':'primary'}`} onClick={()=>toggleZone(zone)}>{zone.active?'إيقاف':'تفعيل'}</button></div>)}</div>:<Empty>أضف المناطق الفعلية وأسماء القرى قبل فتح الخدمة.</Empty>}
    <form className="form-grid zone-form" onSubmit={addZone}><label className="field-label">اسم المنطقة<input required value={zoneDraft.name} onChange={e=>setZoneDraft({...zoneDraft,name:e.target.value})} placeholder="اسم القرية أو المنطقة"/></label><label className="field-label">رسوم التوصيل بالجنيه<input required type="number" min="0" step="0.5" value={zoneDraft.fee} onChange={e=>setZoneDraft({...zoneDraft,fee:e.target.value})} placeholder="0"/></label><button className="button primary" disabled={busy}><Plus size={16}/>إضافة منطقة</button></form>
  </Panel><Panel title="متاجر مسجلة"><div className="order-list">{(storesState.data||[]).map(s=><div className="order-row" key={s.id}>{s.image_url&&<img className="product-thumb" src={s.image_url} alt="" loading="lazy"/>}<div><strong>{s.name}</strong><p>{s.profiles?.full_name||'مالك المتجر'} · {s.delivery_zones?.name}</p></div><Status status={s.active?'accepted':'cancelled'} /></div>)}</div></Panel></div>}
 </Shell>;
}

function NativeAuthCallback(){const navigate=useNavigate();useEffect(()=>{if(!Capacitor.isNativePlatform()||!supabase)return;let active=true;let handle;const acceptUrl=async(raw)=>{try{const url=new URL(raw);if(url.protocol!=='com.wosla.delivery:'||url.hostname!=='auth-callback')return;const code=url.searchParams.get('code');if(code){const {error}=await supabase.auth.exchangeCodeForSession(code);if(!error&&active)navigate('/',{replace:true});return;}const params=new URLSearchParams(url.hash.slice(1));const access_token=params.get('access_token');const refresh_token=params.get('refresh_token');if(access_token&&refresh_token){const {error}=await supabase.auth.setSession({access_token,refresh_token});if(!error&&active)navigate('/',{replace:true});}}catch{}};NativeApp.addListener('appUrlOpen',event=>acceptUrl(event.url)).then(listener=>{if(active)handle=listener;else listener.remove();});NativeApp.getLaunchUrl().then(result=>{if(result?.url)acceptUrl(result.url);});return()=>{active=false;handle?.remove();};},[navigate]);return null;}
function NativeBackButton(){useEffect(()=>{if(!Capacitor.isNativePlatform())return;let active=true;let handle;NativeApp.addListener('backButton',({canGoBack})=>{if(canGoBack&&window.history.length>1)window.history.back();else NativeApp.exitApp();}).then(listener=>{if(active)handle=listener;else listener.remove();});return()=>{active=false;handle?.remove();};},[]);return null;}
function AppRoutes(){return <Routes><Route path="/setup" element={<SetupScreen/>}/><Route path="/login" element={<LoginPage/>}/><Route path="/signup" element={<SignupPage/>}/><Route path="/*" element={<AuthGate/>}/></Routes>}
export default function App(){if(!configured)return <SetupScreen/>;return <BrowserRouter><NativeAuthCallback/><NativeBackButton/><AuthProvider><AppRoutes/></AuthProvider></BrowserRouter>; }
function Metric({label,value,icon}){return <div className="metric"><span className="metric-icon">{icon}</span><span className="metric-label">{label}</span><strong>{value}</strong></div>}
